### PR TITLE
tidy-ups

### PR DESCRIPTION
**Pull request by marksmayo**
- consistent string quotes
 - sorted imports
 - consistent indentations
 - fixed spacing -

### CODE REVIEW

**Comment by marksmayo** [comment]
Not sure what the sonar failure means?

**Comment by christianhelle** [comment]
First of all thanks for this contribution

I used PyCharm when writing this and used all the coding styles and formatting suggestions from PyCharm. If you used a tool to make all these changes then it would be great if you can include the configuration files of that tool so I can also start adapting it

**Comment by christianhelle** [comment]
> Not sure what the sonar failure means?

This is because the SONAR_TOKEN GitHub workflow secret is inaccessible from your fork branch. If I made you a contributor to this repository, you can run the SonarCloud workflow. 

I think I'll do that since you have already contributed quality stuff in the past

**Comment by christianhelle** [comment]
> > Not sure what the sonar failure means?
> 
> This is because the SONAR_TOKEN GitHub workflow secret is inaccessible from your fork branch. If I made you a contributor to this repository, you can run the SonarCloud workflow.
> 
> I think I'll do that since you have already contributed quality stuff in the past

According to Github:
> Anyone with collaborator access to this repository can use these secrets and variables for actions. They are not passed to workflows that are triggered by a pull request from a fork.

I added you as a contributor to this repo so you should be able to create branches directly instead of forking.

**Pull request merged**
