### PR TITLE
fix: ValueError: mutable default <class 'list'> for field x is not alowed: use default_factory

### PR DESCRIPTION
**Pull request by flobz**
Hello,
This PR allow to use list of element in dataclass.

### CODE REVIEW

**Comment by flobz** [comment]
I fixed the compatibility with python3.7

**Comment by christianhelle** [comment]
@flobz Thanks for your contribution. The changes look good to me and my only concern was that the tests were failing in Python 3.7 and 3.8

Let's get these changes merged in and released as soon as all tests are green

**Comment by christianhelle** [comment]
@flobz your contribution is now released to PyPi as [v1.0.19](https://pypi.org/project/autofaker/1.0.19/)

**Comment by flobz** [comment]
Thanks

**Pull request merged**
